### PR TITLE
Validation sync errors

### LINKED ISSUE #612: Fix validation errors
### _Type_:
Issue

### _What happened? / What do you need?_:
Validator tests often fail with errors:
```
  Scenario: Re-Start mining
    Given I have the following accounts:
      Error: timeout error: node is synchronised
```

```
--- Failed steps:

  Scenario: Re-Start mining
    And I wait for my node to be synced
      Error: timeout error: timeout waiting for node sync
```

### _If it's an issue, how can we reproduce it?_:
Run validator tests many times

### _Priority_:
Medium

### PR DESCRIPTION
**Pull request by JekaMas**
The first iteration to make the validation process error-free.

Closes #612 https://github.com/kowala-tech/kcoin/issues/519

### CODE REVIEW

File: client/core/types/chunk.go [hunk 1]
```diff
@@ -108,29 +113,49 @@ func (ds *DataSet) Size() uint {
...
 	// exists
+
+	ds.l.RLock()
+	defer ds.l.RUnlock()
 	return ds.data[i]
 }
 
-func (ds *DataSet) Add(chunk *Chunk) {
+func (ds *DataSet) Add(chunk *Chunk) error {
+	if chunk == nil {
```
Comment (acroca) [inline client/core/types/chunk.go]: I like this as a safety measure. But would be nice as well to detect when this situation happened and avoid it too.

File: client/core/types/vote.go [hunk 2]
```diff
@@ -217,3 +218,39 @@ func (vote *Vote) String() string {
...
+	return &VotesSet{m: make(map[common.Hash]*Vote)}
+}
+
+func (v *VotesSet) Add(vote *Vote) {
+	v.l.Lock()
+	v.m[vote.Hash()] = vote
+	v.l.Unlock()
+}
+
+func (v *VotesSet) Has(h common.Hash) bool {
```
Comment (acroca) [inline client/core/types/vote.go]: I'd rename it to `ContainsHash`.
Similar data structures use `Contains` instead of `Has` to check if an item is in the collection.
Also adding the `Hash` part is because his is a `VoteSet`, so I'd assume a `Contains` function would receive a `Vote` to check if it exists, so if we're checking its hash I think it's clearer to name it that way.

File: client/core/types/vote.go [hunk 3]
```diff
@@ -217,3 +218,39 @@ func (vote *Vote) String() string {
 }
 
 type Votes []*Vote
```
Comment (acroca) [inline client/core/types/vote.go]: Is the `VoteSet` a replacement for `Votes` or we still use both?

File: client/core/types/vote.go [hunk 4]
```diff
@@ -217,3 +218,39 @@ func (vote *Vote) String() string {
...
+
+type VotesSet struct {
+	m map[common.Hash]*Vote
+	l sync.RWMutex
+}
+
+func NewVotes() *VotesSet {
```
Comment (acroca) [inline client/core/types/vote.go]: `NewVoteSet` better, no?

File: client/core/voting_table.go [hunk 5]
```diff
@@ -31,22 +31,25 @@ func NewVotingTable(voteType types.VoteType, voters types.Voters, majority Quoru
...
+		votes:    types.NewVotes(),
 		quorum:   TwoThirdsPlusOneVoteQuorum,
 		majority: majority,
 	}, nil
 }
 
-func (table *votingTable) Add(vote types.AddressVote) error {
-	if !table.isVoter(vote.Address()) {
-		return fmt.Errorf("voter address not found in voting table: %#x", vote.Address().Hash())
+func (table *votingTable) Add(voteAddressed types.AddressVote) error {
```
Comment (acroca) [inline client/core/voting_table.go]: you could call it `addressVote`, maps better with `types.AddressVote` :)

File: client/knode/validator/validator.go [hunk 6]
```diff
@@ -625,7 +630,7 @@ func (val *validator) AddBlockFragment(blockNumber *big.Int, round uint64, fragm
 		err = val.chain.Validator().ValidateState(block, parent, val.state, receipts, usedGas)
 		if err != nil {
 			val.handleMutex.Unlock()
-			log.Crit("Failed to validate the state", "err", err)
+			log.Error("Failed to validate the state", "err", err)
```
Comment (acroca) [inline client/knode/validator/validator.go]: I'm worried about all those `Crit` to `Error`. I guess they were `Crit` because the state of the current process is invalid so we have to crash the process. Moving it to error means the process will continue. Is it fine? Will the state get fixed?

File: client/core/voting_table.go (hunk 5 above)
Comment (JekaMas) [reply client/core/voting_table.go]: I'm logging the request in https://github.com/kowala-tech/kcoin/pull/613/files#diff-658294a439327f8305b9d63bf426c417R581

File: client/core/types/vote.go (hunk 2 above)
Comment (JekaMas) [reply client/core/types/vote.go]: I do like `Contains(vote *Vote)` to hide the imlementation

File: client/core/types/vote.go (hunk 3 above)
Comment (JekaMas) [reply client/core/types/vote.go]: We still use both. `Votes` is used where we write new data to the commit to the DB.

File: client/core/types/chunk.go (hunk 1 above)
Comment (JekaMas) [reply client/core/types/chunk.go]: I'm logging the request in https://github.com/kowala-tech/kcoin/pull/613/files#diff-658294a439327f8305b9d63bf426c417R581

File: client/core/types/vote.go (hunk 4 above)
Comment (JekaMas) [reply client/core/types/vote.go]: Sure.

File: client/knode/validator/validator.go [hunk 7]
```diff
@@ -578,20 +578,27 @@ func (val *validator) vote(vote *types.Vote) {
...
+	if err := val.blockFragments.Add(fragment); err != nil {
+		err = errors.New("Failed to add a new block fragment: " + err.Error())
+		return err
+	}
 
 	if val.blockFragments.HasAll() {
 		block, err := val.blockFragments.Assemble()
 		if err != nil {
-			log.Crit("Failed to assemble the block", "err", err)
+			err = errors.New("Failed to assemble the block: " + err.Error())
```
Comment (JekaMas) [inline client/knode/validator/validator.go]: @acroca I'll keep `Error` here because `Assemble` doesn't change DB state and using `Crit` leads to the possibility to kill any node in the Network just sending it an incorrect block fragment.

File: client/core/types/vote.go (hunk 3 above)
Comment (acroca) [reply client/core/types/vote.go]: Ok
