### PR TITLE
Bug/validator data races#496

### LINKED ISSUE #496: Exception running a new validator
I've got this error while running a new validator:
```
WARN [07-06|13:56:07] Joining the network 2 with a deposit 5000000000000000000. Account "0xFc4e2a1b223285CEd807180956A1792a83161d2A" 
INFO [07-06|13:56:07] Submitted transaction                    fullhash=0x4a1bd384edc85b4212d6b176b04bede4051fccd24607e170ddbfb3159ecb4f24 recipient=0x6f04441A6eD440Cc139a4E33402b438C27E97F4B
INFO [07-06|13:56:07] Waiting confirmation to participate in the consensus 
INFO [07-06|13:56:08] Imported new chain segment               blocks=1 txs=1 mgas=0.199 elapsed=1.678ms   mgasps=118.684 number=19 hash=4dc604…5b542d
INFO [07-06|13:56:08] Starting validation operation 
INFO [07-06|13:56:08] Voter has been accepted in the election 
INFO [07-06|13:56:08] Starting a new election 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7e3726]

goroutine 129 [running]:
github.com/kowala-tech/kcoin/client/core/types.(*DataSet).Add(0x0, 0xc421932880)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/core/types/chunk.go:123 +0x26
github.com/kowala-tech/kcoin/client/knode/validator.(*validator).AddBlockFragment(0xc42025ca80, 0xc421931060, 0x0, 0xc421932880, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/validator/validator.go:580 +0x90
github.com/kowala-tech/kcoin/client/knode.(*ProtocolManager).handleMsg(0xc4201d24b0, 0xc420dc0630, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:648 +0x81a
github.com/kowala-tech/kcoin/client/knode.(*ProtocolManager).handle(0xc4201d24b0, 0xc420dc0630, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:279 +0x6cb
github.com/kowala-tech/kcoin/client/knode.NewProtocolManager.func1(0xc420d75440, 0x192ee40, 0xc420232310, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:123 +0x1f2
github.com/kowala-tech/kcoin/client/p2p.(*Peer).startProtocols.func1(0xc420232310, 0xc420d75440, 0x192ee40, 0xc420232310)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/peer.go:332 +0x66
created by github.com/kowala-tech/kcoin/client/p2p.(*Peer).startProtocols
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/peer.go:331 +0x228
```

/cc @rgeraldes

### PR DESCRIPTION
**Pull request by JekaMas**
I've tried to extract the smallest possible part of validator as a thread-safe interface.
It still needed to think about `validator` in the context of thread-safety in the future.

Closes #496

### CODE REVIEW

File: client/knode/validator/validator.go [hunk 1]
```diff
@@ -39,20 +39,24 @@ type Backend interface {
...
-	Running() bool
 	SetCoinbase(walletAccount accounts.WalletAccount) error
 	SetDeposit(deposit *big.Int) error
 	Pending() (*types.Block, *state.StateDB)
 	PendingBlock() *types.Block
+	Deposits(address *common.Address) ([]*types.Deposit, error)
+	RedeemDeposits() error
+}
+
+type ValidatorSafe interface {
```
Comment (jmatosp) [inline client/knode/validator/validator.go]: sorry but this name helps nothing understating what it does. lets try a few?

maybe:

Validator -> Manager/Service
ValidatorSafe -> Validator

more suggestions?

File: client/knode/protocol/const.go [hunk 2]
```diff
@@ -8,18 +8,21 @@ import (
...
 const (
 	Kcoin1 = 1
+
+	// Official short name of the protocol used during capability negotiation.
+	ProtocolName = "kcoin"
 )
 
-// Official short name of the protocol used during capability negotiation.
-const ProtocolName = "kcoin"
+var (
```
Comment (jmatosp) [inline client/knode/protocol/const.go]: I think this would sit better in a struct/object

File: client/p2p/discv5/udp.go [hunk 3]
```diff
@@ -437,3 +440,46 @@ func decodePacket(buffer []byte, pkt *ingressPacket) error {
 	err = s.Decode(pkt.data)
 	return err
 }
+
+// IsDiscoveryPacket returns nil error if a packet is a DiscoveryV5 KCOIN packet
+// it's a kind of 'bad and fast' code to make dropping non-kcoin connections as fast as possible
+func IsDiscoveryPacket(buffer []byte) error {
```
Comment (jmatosp) [inline client/p2p/discv5/udp.go]: can't read this method, can you split so it's easier to  understand

File: client/knode/validator/validator.go (hunk 1 above)
Comment (JekaMas) [reply client/knode/validator/validator.go]: I like this naming. How do you think, maybe the opposite naming is better:
Validator -> Validator
ValidatorSafe -> Service ?

File: client/knode/protocol/const.go (hunk 2 above)
Comment (JekaMas) [reply client/knode/protocol/const.go]: I can do that.

File: client/p2p/discv5/udp.go (hunk 3 above)
Comment (JekaMas) [reply client/p2p/discv5/udp.go]: I'll try, but it's a really low-level method...

**Comment by JekaMas** [comment]
@jmatosp ping

**Comment by jmatosp** [comment]
Pong

**Comment by JekaMas** [comment]
@jgimeno CR, please.

File: client/p2p/discv5/udp.go [hunk 4]
```diff
@@ -122,7 +124,7 @@ type (
 )
 
 var (
-	//fixme: @jekamas use a shorter prefix. Breaking change!
+	//fixme: @jekamas use a shorter Prefix. Breaking change!
```
Comment (acroca) [inline client/p2p/discv5/udp.go]: hm

File: client/knode/protocol/const.go [hunk 5]
```diff
@@ -1,26 +1,38 @@
...
 
-// Official short name of the protocol used during capability negotiation.
-const ProtocolName = "kcoin"
+	// Official short name of the protocol used during capability negotiation.
+	ProtocolName = "kcoin"
+)
 
-// Supported versions of the kcoin protocol (first is primary).
-var ProtocolVersions = []uint{Kcoin1}
+var Consts = struct {
```
[the remark this answers is not in the document]
Comment (jgimeno) [reply client/knode/protocol/const.go]: Sorry but are you sure Constants is the way to go?

[the remark this answers is not in the document]
Comment (acroca) [reply client/knode/protocol/const.go]: for some reason I got confused with `consts`, I had to double check its implementation to make sure it's really a plural of const and not something else. `specs`, `config`, and `prefs` are more common abbreviations I think.
Anyway maybe this is just me. Your call.

File: client/p2p/discover/udp.go [hunk 6]
```diff
@@ -519,6 +519,13 @@ func (t *udp) readLoop(unhandled chan<- ReadPacket) {
 	buf := make([]byte, 1280)
 	for {
 		nbytes, from, err := t.conn.ReadFromUDP(buf)
+		if err := discv5.IsDiscoveryPacket(buf); err == nil {
+			unhandled <- ReadPacket{buf[:nbytes], from}
+			continue
+		} else {
+			fmt.Println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!", err)
```
[the remark this answers is not in the document]
Comment (JekaMas) [reply client/p2p/discover/udp.go]: It's a debug message and should be removed. In case of any error, it'll be caught below.

A nice catch!

File: client/p2p/discv5/udp.go (hunk 4 above)
Comment (JekaMas) [reply client/p2p/discv5/udp.go]: Auto replace, will fix it.

**Comment by JekaMas** [comment]
@acroca All tests are 'green' and fixes have been made.

File: client/p2p/discover/udp.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (acroca) [reply client/p2p/discover/udp.go]: hard to miss :D

File: client/p2p/discv5/packet.go [hunk 7]
```diff
@@ -0,0 +1,157 @@
+package discv5
```
Comment (jmatosp) [inline client/p2p/discv5/packet.go]: there is a known pattern to solve this problem (specification pattern), that is a bit less rigid, but as is it's easy to understand.
